replicaCount: 3

image:
  repository: greenmqtt
  tag: local
  pullPolicy: IfNotPresent

fullnameOverride: greenmqtt

persistence:
  enabled: false

service:
  type: ClusterIP

greenmqtt:
  storageBackend: memory
  extraEnv:
    GREENMQTT_STATE_MODE: "replicated"
    GREENMQTT_METADATA_BACKEND: "replicated"
    GREENMQTT_METADATA_ENDPOINT: "http://greenmqtt-state:50051"
    GREENMQTT_RANGE_ENDPOINT: "http://greenmqtt-state:50051"
    GREENMQTT_PEERS: ""

storeTopology:
  enabled: true
  replicaCount: 1
  greenmqtt:
    storageBackend: rocksdb
